# Generated by Django 5.0.7 on 2024-07-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact',
        ),
    ]
