# Generated by Django 5.0.7 on 2024-07-23 12:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0002_rename_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('flavor', models.CharField(max_length=122)),
                ('quantity', models.CharField(max_length=122)),
                ('date', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('delivery_address', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
