# Generated by Django 5.0.7 on 2024-07-23 21:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0006_remove_contact_contact_id_remove_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
