# Generated by Django 5.0.7 on 2024-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0008_icecreamflavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreamflavor',
            name='image',
            field=models.ImageField(upload_to='icecream_flavors/Upload'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
