# Generated by Django 5.0.7 on 2024-07-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='03419993979', max_length=11),
            preserve_default=False,
        ),
    ]
