# Generated by Django 5.1 on 2024-08-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0015_remove_order_order_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecreamflavor',
            old_name='price_1kg',
            new_name='price_per_gram',
        ),
        migrations.RemoveField(
            model_name='icecreamflavor',
            name='price_250g',
        ),
        migrations.RemoveField(
            model_name='icecreamflavor',
            name='price_500g',
        ),
    ]
