# Generated by Django 5.1 on 2024-09-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0017_alter_order_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IceCreamFlavor',
            new_name='MasalaFlavor',
        ),
    ]
