# Generated by Django 5.1 on 2024-09-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0021_remove_order_flavor_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='masalaflavor',
            name='category',
            field=models.CharField(choices=[('Masala', 'Masala'), ('Atta', 'Atta'), ('Home Remedies', 'Home Remedies')], default='Masala', max_length=20),
        ),
    ]
