# Generated by Django 5.0.7 on 2024-09-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0027_order_date_confirmed_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='received', max_length=10),
        ),
    ]
