# Generated by Django 5.0.7 on 2024-09-06 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0028_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shipped',
            new_name='date_processed',
        ),
    ]
