# Generated by Django 5.0.7 on 2024-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0030_order_date_shipped_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'active')], default='pending', max_length=10),
        ),
    ]
