# Generated by Django 5.0.7 on 2024-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0031_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_pickup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('selfpickup', 'Self Pickup')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='time_pickup',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
