# Generated by Django 5.0.7 on 2024-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0032_order_date_pickup_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('COD', 'COD'), ('selfpickup', 'Self Pickup')], default='COD', max_length=10),
        ),
    ]
