# Generated by Django 5.0.7 on 2024-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearlfoods', '0037_product_alter_cartitem_flavor_delete_masalaflavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('grams', 'Grams'), ('kgs', 'Kgs'), ('packet', 'Packet'), ('litre', 'Litre')], default='grams', max_length=10),
        ),
    ]
